### ISSUE TITLE
Add pdf version

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ukgovdatascience/rap_companion#46]

**Comment by nacnudus** [comment]
@ivyleavedtoadflax Wary as I am of closing your issues :stuck_out_tongue: I think this was a good idea at the time, but since then GOV.UK has [blogged](https://gds.blog.gov.uk/2018/07/16/why-gov-uk-content-should-be-published-in-html-and-not-pdf/) about why PDF is a bad idea (accessibility).  The content of the companion is now also available on the [RAP website](https://ukgovdatascience.github.io/rap-website/companion-index.html), which uses the GOV.UK Design System and seems to print quite nicely to PDF (I think the design system bears this use case in mind).

**Comment by ivyleavedtoadflax** [comment]
Agree!
