### ISSUE TITLE
Plain English

### ISSUE THREAD

**Issue by tjtnew** [ukgovdatascience/rap_companion#80]
Consider writing some sections more plainly.  For example, the language used in the section below could be simplified and the sentenced shortened: 
https://github.com/ukgovdatascience/rap_companion/blob/da7079747407115d749848fede72e083bbc27ba3/01-Introduction.Rmd#L7

**Comment by nacnudus** [comment]
@tjtnew thanks for opening this issue.  I've migrated it to the RAP website repo where it is now more relevant https://github.com/ukgovdatascience/rap-website/issues/2.

I'll close this one because the original RAP Companion is going to be left alone so that we don't accidentally undermine the MOOC, which refers to it.  I would be very grateful for a review of the new content (not the RAP companion, which will gradually be superseded) according to the GOV.UK guidelines https://www.gov.uk/guidance/content-design/writing-for-gov-uk.
