### ISSUE TITLE
Make the companion accessible for all

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/rap_companion#83]
As per [the Service Manual](https://www.gov.uk/service-manual/helping-people-to-use-your-service/making-your-service-accessible-an-introduction#meeting-the-accessibility-standard).

I ran the Companion through tenon.io, an online resource for detecting accessibility issues.  Apparently there are 629 issues at time of writing. I've saved [a CSV of the report as a gist](https://gist.github.com/matt-dray/e490ae3d597bb312c3249c31b37147ab). You can [click here to re-run the tenon.io report online](https://tenon.io/testNow.php?url=https://ukgovdatascience.github.io/rap_companion/).

**Comment by matt-dray** [comment]
Probable actions:
- [ ] Fix issues identified by tenon.io or other sources
- [ ] Adjust CONTRIBUTING.md with advice and link to Service Manual
- [ ] Do user research with the companion to find stumbling blocks (could be done with #80 in mind as well)

**Comment by nacnudus** [comment]
Firstly: :flushed: 

* Bookdown [book](https://info340.github.io/standards-and-accessibility.html) that talks about accessibility but doesn't seem to have customised bookdown itself? 
* Conference [talk](https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/mobile/TypeSearchAbstractDetails.cfm?AbstractID=332845&SessionID=215953&type=2&subtype=3)
* Bookdown [template](https://github.com/jmlondon/uswebr) for US Web Design standards, including WCAG.
* @matt-dray's [post](https://community.rstudio.com/t/making-shiny-apps-accessible-for-all-humans/8458/5) on the RStudio Community, with some helpful replies.

**Comment by nacnudus** [comment]
Perhaps styling it with the [GOV.UK Design System](https://design-system.service.gov.uk/) would help.

It turns out this is harder than a mere yaml setting:

```yaml
output:
  html_document:
    css: govuk.css
```

The design system uses classes, so to style `<h1>foo</h1>` you have to do `<h1 class="govuk-heading-xl">foo</h1>`, which means you need to write a pandoc [filter](https://pandoc.org/lua-filters.html) -- and Lua seems easier than Haskell -- that modifies the Abstract Syntax Tree representation of the document.

```lua
function Header(elem)
  level = elem.level
  content = elem.content
  identifier = elem.attr.identifier
  if level == 1 then
    attr = pandoc.Attr(identifier, {"govuk-heading-xl"})
  elseif level == 2 then
    attr = pandoc.Attr(identifier, {"govuk-heading-l"})
  elseif level == 3 then
    attr = pandoc.Attr(identifier, {"govuk-heading-m"})
  elseif level == 4 then
    attr = pandoc.Attr(identifier, {"govuk-heading-s"})
  elseif level == 5 then
    attr = pandoc.Attr(identifier, {"govuk-body-l"})
    return pandoc.Para(pandoc.Span(content, attr))
  end
  return pandoc.Header(level, content, attr)
end
```

And then in the yaml you put something like

```yaml
output:
  html_document:
    css: ./node_modules/govuk-frontend/govuk.css
    pandoc_args: [
           --lua-filter, ./govuk.lua
        ]
    section_divs: no
    theme: null
```

Why `section_divs: no`?  Otherwise the header and its body text (and nested headers) are wrapped in a `<div>`, the class is added to the `<div>`, so the body is styled like a header too.

Where does `govuk.css` come from?  You have to compile the sass in the Design System after you 'install' it (basically downloads the `node_modules` directory.  There's an [R package for that](https://github.com/rstudio/sass).

**Comment by nacnudus** [comment]
I've clone the content of the companion to the [RAP website](https://ukgovdatascience.github.io/rap-website/companion-index.html), built on [govdown](https://github.com/ukgovdatascience/govdown), which uses accessible components from the [GOV.UK Design System](https://design-system.service.gov.uk).  The original RAP Companion [bookdown website](https://ukgovdatascience.github.io/rap_companion/) will remain as-is because it's too hard to fix and we should break compatibility with the MOOC.

I'll add subsequent steps as govdown or rap-website issues, e.g. testing in the empathy lab.
